### ISSUE TITLE
Looks like our last changes don't work.

### ISSUE THREAD

**Issue by VictorDuma-zz** [lancaster-university/codal-brainpad#2]
Our new changes to firmware with new bootloader work only locally in the codal. On makecode don't. Need it rebuild codal-brainpad target with lock mode? I mean changes in the target-locked.json.

**Comment by finneyj** [comment]
Hi @VictorDuma 

Very likely! This will generate a version tagged release that MakeCode uses for version control...

To generate a locked version from the current build:

```
python build.py -l
```

or if you prefer:
```
python build.py --lock
```
